title: <img src="./logo.svg" alt="LoAT">
email: florian.frohn@cs.rwth-aachen.de
description: >- # this means to ignore newlines until "baseurl:"
  We present the new version of the Loop Acceleration Tool (LoAT), a
  powerful tool for proving non-termination and worst-case lower bounds for programs
  operating on integers.
github_username:  ffrohn
theme: jekyll-theme-cayman
